### ISSUE TITLE
Generate too short/long RSA and DSA keys for tests

### ISSUE THREAD

**Issue by ojarva** [ojarva/python-sshpubkeys#1]

**Comment by alertedsnake** [comment]
I just hit this issue with a ssh-dss key with 2048 bits, your library limits that to 1024 bits (line 150).  This is certainly a valid key.

Any plans to fix this?

**Comment by alertedsnake** [comment]
Weird - I can't figure out how this user did this, since the spec says 1024 and I can't actually make one larger either.  Fascinating!

**Comment by ojarva** [comment]
Yep. Spec says only 1024 is valid, so I'm checking against that. Does that 2048 bit key actually work with i.e. OpenSSH?

**Comment by alertedsnake** [comment]
Yeah, the 2048 bit key he generated actually does work, we didn't notice anything wrong until I tried to read it with your library.  Still no idea how he generated it, and he doesn't remember.

We've replaced it though, because the spec says 1024, so I'm not going to consider this a bug - up to you if you want to actually support them :)

**Comment by ojarva** [comment]
I'm considering adding option for allowing >1024bit DSA keys. By default validation should follow the spec. ssh-keygen does not allow generating non-standard DSA keys but some other tool will do that without complaining.

**Comment by ojarva** [comment]
Related: https://github.com/ojarva/python-sshpubkeys/issues/9
